// Case study content. Edit here; every page is generated from this list.
export interface Section { id: string; title: string; body?: string[]; cards?: string[][]; figs?: string[][]; two?: boolean }
export interface CaseStudy {
  slug: string; featured?: boolean; title: string; who: string; client?: string; hue: string; cover: string;
  summary: string; tags: string[]; platform: string; tools?: string[]; status?: string; role?: string;
  team?: string; resp?: string; timeline?: string; findings?: string[][]; metrics?: string[][];
  problem: string; approach: string; sections: Section[]; outcome: string; learnings?: string[][];
  prototype?: string; external?: string;
}
export const CONTACT = { linkedin: 'https://www.linkedin.com/in/alfonzolouw', cv: '' }; // add URLs before deploying; empty links stay hidden
export const TOOLS = ['Figma','Illustrator','Photoshop'];
export const ROLE = 'Senior Product Designer';
export const CASES: CaseStudy[] = [
  {slug:'momo-p2p', featured:true, title:'MoMo Send Money', who:'MTN MoMo', hue:'#FFCB05', cover:'momo_inuse',
   summary:'Smart wallet detection that shows which wallets a number has and points people to the free, instant MoMo option, with beneficiaries saved in the same flow.',
   tags:['P2P payments','Smart wallets','Beneficiaries'], platform:'Mobile money app', tools:['Figma','HTML prototypes'],
   status:'Live', team:'I’m the only designer, with about 5 people involved in testing', resp:'I run the research and design myself and play it back to the team.', findings:[['A number can have a MoMo wallet, another operator\u2019s wallet, or both, and people couldn\u2019t tell which was fastest or cheapest.', 'Wallets are detected as soon as the number is entered. MoMo is recommended with Instant Transfer, Zero fees and a Free badge.'], ['When a number has no MoMo wallet, the payment hit a dead end.', 'The card says so plainly and offers other wallets, such as Orange, so the transfer still goes through.'], ['Saving someone for next time was a separate journey after the payment.', 'Save as beneficiary is a checkbox inside the payment, and recent beneficiaries sit at the top for one-tap repeat transfers.']], metrics:[['Uplift', '', 'How much better the new design performs than the original, as a percentage. Tested against the original in A/B testing.'], ['Task success rate', '', 'Share of people who reach their goal without help. Here: sending money to the right wallet.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from entering a number to a confirmed transfer.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: picking the wrong wallet or mistyping a number.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: transfers completed and repeat sends to saved beneficiaries.']],
   problem:'A phone number can be linked to a MoMo wallet, another operator\u2019s wallet, or both, and each option has a different cost and speed. People shouldn\u2019t have to guess where their money is going. Saving someone for next time was also a separate journey from sending money.',
   approach:'As soon as a number is entered, the app checks which wallets it has. MoMo is recommended when it\u2019s available, clearly labelled Instant Transfer and Zero fees, with other wallets one tap away. Saving the recipient as a beneficiary moved into the payment itself, and everything was built from MoMo\u2019s existing components.',
   sections:[
    {id:'wallets', title:'Smart wallet detection', body:['Send Money starts from the MoMo home screen. Once a number is entered, the card under it responds to what the app finds: several wallets, with the free MoMo option recommended; no MoMo wallet, with other wallets one link away; and other wallets such as Orange shown so the payment can still go through.'],
     figs:[['momo_single','Several wallets found: the free, instant MoMo Wallet is recommended'],['momo_journey','From the home screen to Send Money: MoMo found, no MoMo wallet, other wallets']]},
    {id:'beneficiaries', title:'Beneficiaries in the flow', body:['Recent beneficiaries sit at the top for one-tap repeat payments, and a Save as beneficiary checkbox at the end of the form replaces the separate journey that used to follow a payment.'],
     figs:[['momo_flow','Before and after: saving a beneficiary moves inside the payment']]}
   ],
   outcome:'Live in the MoMo app. People now see which wallets a number has and are pointed to the free, instant MoMo option before they send, with beneficiaries saved in the same flow.'},

  {slug:'momo-bills', featured:true, title:'MoMo Bill payments', who:'MTN MoMo', hue:'#0D3B5E', cover:'bills_cover',
   summary:'One reusable bill payment pattern that every biller plugs into, from the home screen and All Bills to saved bills, pre-paid and post-paid.',
   tags:['Design systems','Bill payments','Scalable patterns'], platform:'Mobile money app', tools:['Figma','HTML prototypes'],
   status:'In build', team:'I’m the only designer, with about 5 people involved in testing', resp:'I run the research and design myself and play it back to the team.', findings:[['Billers hidden behind modals, \u201cSee all\u201d links or default filters made people hunt for the one they needed.', 'All Bills shows every category as a tab and every biller as a tile, with no pop-ups or cut-off lists on the main screen.'], ['Some categories have dozens of providers, too many to scan as tiles.', 'Choosing a provider opens a searchable list with filter chips and counts, such as All (38), Water (19) and Electricity (19).'], ['People pay the same bills every month, often for more than one home.', 'Saved bills like My house, Mom\u2019s house and Gran\u2019s house sit at the top for one-tap repeats, with Save this bill at the end of the form.'], ['Pre-paid and post-paid bills were at risk of becoming separate flows.', 'One form with a Pre-paid or Post-Paid choice, and a Schedule tab next to Pay Bills for recurring payments.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: finding a biller and paying a bill.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from opening All Bills to a paid bill.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: wrong provider, meter number or bill type.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: bills paid and saved bills paid again next month.']],
   problem:'Every new biller risked becoming a one-off flow, with its own entry point, errors and saved bills. People need to find their biller quickly and pay without surprises, and the team needed something that scales to new billers and markets without redesigning each time.',
   approach:'I built a bills template around four use cases: For you / All Bills, post-paid via All Bills, the Pay tab, and post-paid via the Pay tab. Each has its own end-to-end journey: payment, inline errors, recent transactions, saving a bill and managing it. The same structure then carried into new billers, such as MoMo\u2019s utilities in Liberia.',
   sections:[
    {id:'journey', title:'From home to paid', body:['All Bills is one tap from the For you grid on the MoMo home screen. From there, every category (Utilities, TV, School fees, Government bills) is a tab, with each biller shown as a tile. Paying a bill happens on one form: pick a saved bill or a provider, choose pre-paid or post-paid, add the meter number and amount, and save it for next time.'],
     figs:[['bills_journey','Home, All Bills, paying a utility bill and picking a provider']]},
    {id:'template', title:'One template, four journeys', body:['Screens and copy stay specific to each entry point, but underneath they share one payment journey. That keeps the experience consistent and makes each flow easy to read end to end.'],
     figs:[['bills_template','Four entry points sharing one end-to-end payment journey']]},
    {id:'in-view', title:'Every biller in view', body:['People shouldn\u2019t have to hunt for their biller. I set three rules for the bills screen: no modals, no \u201cSee all\u201d truncation and no default filtering, then explored six layouts that keep every provider visible and built each one as an interactive HTML prototype.'],
     figs:[['bills_patterns','Layout directions explored for the bills screen']]},
    {id:'scale', title:'Scaling to new billers', body:['For MoMo Liberia, electricity, water and solar providers were built on the same pattern from the MVP1 requirements and the existing USSD flow, keeping the pattern unchanged and applying each biller\u2019s rules on top.'],
     figs:[['bills_scale','Liberia utilities built on the bills template']]}
   ],
   outcome:'A single bills pattern that new billers plug into, so adding a provider means applying the template rather than designing a new flow.'},

  {slug:'licence-renewal', featured:true, title:'Licence renewal', who:'FNB \u00d7 RTMC', hue:'#2F7D6D', cover:'lic_cover',
   summary:'Vehicle licence renewal inside the FNB app, from documents to payment, with no queue.',
   tags:['Service design','A/B testing','UI'], platform:'iOS and Android',
   problem:'Renewing a vehicle licence usually means a trip to a government office and a long line.',
   approach:'The goal was a secure, convenient way to handle the whole renewal in the app: document submission, payment and notifications. I benchmarked existing services, tested alternatives and designed the final flow with a clickable prototype.',
   sections:[
    {id:'competitors', title:'Competitor analysis', body:['I compared existing renewal services on experience, interface and features to find the standards to meet and the gaps we could use to stand out.'], figs:[['lic_comp','Existing renewal services']]},
    {id:'testing', title:'A/B testing', body:['Alternative screen directions were tested with users before committing to a final design.'], figs:[['lic_ab','A/B test directions']]},
    {id:'design', title:'Final design', figs:[['lic_final','Final renewal flow']]}
   ],
   status:'Live', team:'7 designers, 4 CX specialists and 4 developers', resp:'I did the design and research myself, played it back to the team, and ran A/B testing alongside another designer.', findings:[['Existing renewal services, like the NaTIS portal, were dense menus with little guidance.', 'The FNB flow explains the requirements upfront: the vehicle in My garage, fines paid, and delivery within 14 days.'], ['The tested checkout ran to four steps and relied on a separate no-refund warning just before payment.', 'The final flow shows five clear steps at the start, a progress bar throughout, and a checkout that asks people to confirm their vehicles before paying.'], ['Fees were split across the renewal fee, admin fee, delivery and late fees.', 'The payment overview groups each vehicle with its own breakdown and one total, and delivery addresses can be picked on a map.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: renewing a licence disc.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from starting a renewal to payment.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: missed documents or incorrect delivery details.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: renewals completed and customers renewing again next year.']],
   outcome:'Live in the FNB app. After A/B and usability testing it was rolled out to customers, who can now renew a vehicle licence, submit documents, pay and get notified without visiting a government office.',
   learnings:[['Users don\u2019t always behave how you expect','Data from usability tests guided better outcomes than personal taste.'],['Testing early saves time','Even rough wireframes uncovered usability issues before high-fidelity design.'],['User feedback is everything','Real insight came from listening to pain points rather than assuming them.']],
   prototype:'https://www.figma.com/proto/8EifHT9N6xIVuWN2h1Rswa/Work-projects?page-id=2025:112983&node-id=2025-113026&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2025:112985'},

  {slug:'sell-a-vehicle', featured:true, title:'Sell a vehicle', who:'FNB \u00d7 Car Scan', hue:'#C8323A', cover:'sell_cover',
   summary:'Helping owners capture great photos and a diagnostic report, then sell their car through the FNB app.',
   tags:['End-to-end flow','A/B testing','Prototyping'], platform:'iOS and Android',
   problem:'Selling a car depends on trust. Buyers can\u2019t easily judge a vehicle\u2019s condition from a listing, and sellers struggle to present their car well.',
   approach:'We let owners capture high-quality photos and list their vehicle on FNB\u2019s platform, while sensor data generates a real-time diagnostic report so issues surface before listing. Photos plus mechanical insight make resale more transparent and faster.',
   sections:[
    {id:'competitors', title:'Competitor analysis', body:['I looked at what\u2019s working in the market, what isn\u2019t, and where we could lead rather than follow.'], figs:[['sell_comp','Competitor review']]},
    {id:'testing', title:'A/B testing', body:['Competing listing layouts were tested before the final direction was chosen.'], figs:[['sell_ab','A/B test directions']]},
    {id:'design', title:'Final design', figs:[['sell_final','Final screens'],['sell_mock','Listing and diagnostic report']]}
   ],
   status:'Live', team:'7 designers, 4 CX specialists and 4 developers', resp:'I did the design and research myself, played it back to the team, and ran A/B testing alongside another designer.', findings:[['Listing layouts were tested three ways: a large photo with thumbnails, a swipeable photo card, and compact rows.', 'The final listing uses a swipeable photo gallery with key specs as chips: year, mileage, gearbox, fuel and body type.'], ['Sellers needed help taking photos buyers can trust.', 'Guided capture with an angle-by-angle photo checklist, a photo guide and framing guides in the camera.'], ['Condition was hard for buyers to judge from photos alone.', 'An optional Boost my listing adds an automated exterior condition report, blurs the licence plate and ranks the listing higher.']], metrics:[['Uplift', '', 'How much better the new design performs than the original, as a percentage. Tested against the original in A/B testing.'], ['Task success rate', '', 'Share of people who reach their goal without help. Here: listing a vehicle with all required photos.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from starting a listing to publishing it.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: missing or unusable photos and incomplete details.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: listings published and sellers who list again.']],
   outcome:'Live in the FNB app. After A/B and usability testing it was rolled out to customers, who can photograph their car, get a diagnostic report and list it for sale in one flow.',
   learnings:[['Constraints fuel creativity','Working within tech, compliance and timeline limits often sparked better solutions.'],['Good design requires alignment','Early alignment with stakeholders saved time in the final stages.'],['Small tweaks, big wins','Minor changes to spacing, labels and flows had a major impact.']],
   prototype:'https://www.figma.com/proto/8EifHT9N6xIVuWN2h1Rswa/Work-projects?page-id=2003:108928&node-id=2003-109902&p=f&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2003:109902'},

  {slug:'momo-dashboard', featured:true, title:'MoMo dashboard', who:'MTN MoMo', hue:'#0D3B5E', cover:'dash_cover',
   summary:'A redesigned MoMo home screen with accessible tabs, a personalised Lifestyle section and recent transactions up front, adapted for each market.',
   tags:['Dashboard','Accessibility','Personalisation'], platform:'Mobile money app', tools:['Figma'],
   status:'Delivered', team:'I\u2019m the only designer, with about 5 people involved in testing', resp:'I run the research and design myself and play it back to the team.',
   findings:[['Tabs were small, all caps and cut off, with \u201cFinancial Servi\u2026\u201d running off the screen.', 'Sentence-case tabs with full labels, larger tap targets and a clear selected state, reworked for accessibility.'], ['People had to go looking for features, with only three shortcuts and a banner on home.', 'Favourite recipients and eight services now sit on the home screen, from Transfers and Pay Bills to Save, Invest and Insure.'], ['Useful features stayed hidden unless people already knew where to find them.', 'A Lifestyle section surfaces features like travel, event tickets and food, set per OpCo and tuned with machine learning.'], ['Recent activity sat a level deeper than the dashboard.', 'Recent transactions moved up onto the dashboard, making it easier to check activity and discover what to do next.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: finding a feature from the home screen.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from opening the app to starting a task.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: wrong taps before reaching the right feature.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: features used from Lifestyle and people returning to the app.']],
   problem:'The original dashboard offered three shortcuts and a banner. Tabs were small, all caps and cut off, features were hard to discover, and recent activity lived a level deeper.',
   approach:'I reworked the tabs for accessibility, brought favourite recipients, a fuller services grid and recent transactions onto the home screen, and introduced a Lifestyle section that exposes features per OpCo, tuned with machine learning.',
   sections:[
    {id:'before-after', title:'Before and after', body:['The new home screen keeps the wallet at the top and builds everything people use most around it, so less is hidden behind menus.'],
     figs:[['dash_compare','Before and after, with the four main changes']]},
    {id:'markets', title:'Built for each market', body:['The structure stays the same across MoMo markets, while the services, Lifestyle content and currency are set per OpCo. Ghana and C\u00f4te d\u2019Ivoire share one layout but surface different features.'],
     figs:[['dash_opco','The same dashboard in Ghana and C\u00f4te d\u2019Ivoire']]}
   ],
   outcome:'A home screen that shows more of MoMo at a glance: accessible tabs, favourites and services up front, a personalised Lifestyle section and recent transactions on the dashboard.'},

  {slug:'speedee', title:'Speedee', who:'FNB', hue:'#0E8C8C', cover:'speedee_cover',
   summary:'Tap-on-phone payments that turn a low-cost NFC phone into a card terminal for marketplace sellers.',
   tags:['Research','User flows','A/B testing'], platform:'iOS and Android',
   problem:'FNB wanted Marketplace service providers to take card payments without traditional point-of-sale hardware. The business goal was more digital transactions and revenue, using low-cost, NFC-enabled phones.',
   approach:'I researched how sellers choose payment tools, benchmarked competing mPOS products, then moved from sitemap and flow concepts through wireframes and A/B testing to a final design and prototype.',
   sections:[
    {id:'research', title:'Research', body:['I started with desk research into point-of-sale and mobile POS, especially tap-on-phone, where a phone\u2019s built-in NFC reader accepts cards with no extra hardware. It surfaced nine things every seller weighs up when choosing a payment tool.'],
     cards:[['Business fit','Retail, restaurants and service businesses each need different features.'],['Ease of use','Quick to learn, fast to transact, easy to onboard staff.'],['Hardware','Works with existing phones, card readers and printers.'],['Payment options','Cards, digital wallets and BNPL, with clear fees.'],['Integrations','Stock, loyalty, accounting and sales reporting.'],['Scale','Grows with more users and locations.'],['Security','PCI compliance, encryption and fraud prevention.'],['Cost','Subscription or once-off, transaction fees, hardware.'],['Support','Always-on help, training and reliable uptime.']]},
    {id:'competitors', title:'Competitor analysis', body:['I reviewed competing mPOS products for UX and UI patterns, then shortlisted the features that made payments noticeably easier.'],
     figs:[['speedee_comp','Competitor products reviewed'],['speedee_feat','Features that stood out']]},
    {id:'structure', title:'Sitemap and flows', body:['A mid-level sitemap set Speedee\u2019s entry point in the marketplace. I explored three flow concepts, each for a different user need, and iterated the strongest into the final flow.'],
     two:true, figs:[['speedee_map','Sitemap'],['speedee_flow','User flow concepts']]},
    {id:'wireframes', title:'Wireframes and testing', body:['Low-fidelity wireframes kept the team focused on function first. Two directions were then A/B tested before visual design.'],
     figs:[['speedee_wire','Wireframes'],['speedee_ab','A/B test directions']]},
    {id:'design', title:'Final design', figs:[['speedee_final','Final screens']]}
   ],
   status:'Live', team:'7 designers, 4 CX specialists and 4 developers', resp:'I did the design and research myself, played it back to the team, and ran A/B testing alongside another designer.', findings:[['Competing mPOS products led with hardware features: printouts, dual SIM, offline mode and add-on accessories.', 'Speedee kept to what a phone does well: tap-on-phone card payments, with no extra hardware to buy.'], ['The two A/B directions differed in where the Business tools entry sat: above the list of actions or below it.', 'The final design puts Business tools right under the seller\u2019s profile, with quick actions like Chat, Create payment request and Manage profile in an icon grid.']], metrics:[['Uplift', '', 'How much better the new design performs than the original, as a percentage. Tested against the original in A/B testing.'], ['Task success rate', '', 'Share of people who reach their goal without help. Here: setting up Speedee and taking a first payment.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from sign-up to a first card payment.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: failed taps or incomplete set-up steps.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: sellers activated and sellers still taking payments each month.']],
   outcome:'Live on FNB. Speedee was rolled out to Marketplace sellers after A/B and usability testing, letting them take card payments on the phone they already carry.',
   learnings:[['Problem framing is half the solution','Defining the core problem upfront made every design decision more purposeful.'],['Stakeholder interviews hold hidden gems','Talking to internal teams revealed edge cases and overlooked workflows.'],['Progressive disclosure matters','Giving users information gradually improved comprehension and engagement.']],
   prototype:'https://www.figma.com/proto/fliZ6O3eil65qtdGy2ezRf/AR-DESIGN?page-id=555:26912&node-id=555-26923&p=f&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=555:26923'},

  {slug:'fatca', title:'FATCA reporting', who:'ABSA', hue:'#AF1E45', cover:'fatca_cover',
   summary:'Automating FATCA and CRS tax reporting so operators can classify client data quickly and accurately.',
   tags:['Compliance UX','Workflow design','Desktop'], platform:'Desktop',
   problem:'FATCA and CRS reporting helps tax authorities share information to fight tax evasion. Identifying, remediating and classifying client data for these reports was manual and error-prone.',
   approach:'We designed a desktop tool that automates identification, remediation and classification, with simplified workflows and clear, UI-driven classification.',
   sections:[{id:'design', title:'Final design', two:true, figs:[['fatca_1','Reporting dashboard'],['fatca_2','Classification views']]}],
   status:'Delivered', findings:[['Identifying and classifying client data was manual and error-prone.', 'A reporting dashboard with progress rings and charts shows what\u2019s been classified, and operators work through records in one tool.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: classifying a batch of client records.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: preparing a FATCA or CRS report.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: records classified incorrectly.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: reports submitted on time, cycle after cycle.']],
   outcome:'A manual, error-prone process became an automated tool. Operators identify, remediate and classify client data in one place, with reporting that stays compliant.',
   learnings:[['Balance functionality and simplicity','Simplifying complex workflows improved adoption and reduced errors.'],['Work around constraints','Navigating technical and legal limits taught me to innovate under pressure.'],['Collaborate across teams','Working with developers and compliance kept the tool usable and compliant.']]},

  {slug:'warm', title:'W.A.R.M', who:'Capitec', hue:'#1D4E89', cover:'warm_cover',
   summary:'A secure messaging app that lets relationship managers close, refer or escalate banker requests in one place.',
   tags:['PWA','Internal tools','UI'], platform:'Web and mobile',
   problem:'Transactional bankers and relationship managers were talking on WhatsApp, often from personal accounts or separate bank phones. With no oversight, communication was fragmented, service was inconsistent and nobody was accountable.',
   approach:'WhatsApp for Relationship Managers (W.A.R.M) brings those conversations into a secure, bank-owned app where managers can close, refer or escalate each request quickly.',
   sections:[{id:'design', title:'Final design', figs:[['warm_2','Mobile screens']]}],
   status:'Delivered', findings:[['Banker requests lived in personal WhatsApp chats with no oversight.', 'Chats, Portfolio, Requests and Settings live in one bank-owned app, with read receipts and a clear status on every request.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: closing, referring or escalating a request.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from a banker request to a response.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: requests sent to the wrong person.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: relationship managers using the app every week.']],
   outcome:'Banker requests moved off personal WhatsApp into one secure, bank-owned channel, giving Capitec oversight of every conversation and a clear owner for each request.',
   learnings:[['Design with scalability in mind','Planning for growth helped prevent future UX debt.'],['Constraints fuel creativity','Working within tech and compliance limits sparked better solutions.'],['Good design requires alignment','Early stakeholder alignment saved time at the end.']]},

  {slug:'vitality', title:'Vitality website', who:'Discovery', hue:'#D6246E', cover:'vit_cover',
   summary:'Redesigning the Vitality website as part of a wider rebrand, so products are clearer on every screen.',
   tags:['Web','Responsive','Rebrand'], platform:'Web and mobile',
   problem:'Vitality was rebranding and wanted a website that was easier to use and more visually engaging, so people could understand its products.',
   approach:'I was part of the design team that redesigned the Vitality pages for desktop and mobile.',
   sections:[{id:'design', title:'Final design', figs:[['vit_2','Desktop and mobile pages']]}],
   status:'Delivered', findings:[['People struggled to understand and choose between Vitality\u2019s products.', 'Pages lead with a clear Join today path and show rewards and devices side by side on desktop and mobile.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: finding and understanding a product.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from landing to starting to join.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: dead ends and back-tracking between pages.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: people who start joining and return to the site.']],
   outcome:'Redesigned desktop and mobile pages delivered as part of the Vitality rebrand, with products presented more clearly on every screen size.',
   learnings:[['Function before flash','A beautiful interface means little without a seamless experience.'],['Details make the difference','Microinteractions and type choices change how a product feels.'],['Collaboration is key','Working closely with developers and stakeholders made the product stronger.']]},

  {slug:'pro-find', title:'Pro-Find', who:'Recruitment', client:'Pro-Find', hue:'#EE8A12', cover:'pf_cover',
   summary:'A recruitment app that helps small businesses shortlist faster and lets job seekers browse roles without the paperwork.',
   tags:['Personas','Journey mapping','Mobile'], platform:'Mobile',
   problem:'Small businesses relied on agencies or in-house HR to find candidates, which slowed shortlisting and left critical roles open. Job seekers had to build detailed profiles and upload documents just to browse listings.',
   approach:'We designed for both sides of the hire, grounded in personas and a shared journey map, and validated layouts with users before development.',
   sections:[
    {id:'personas', title:'Personas', body:['Personas for business owners and applicants captured their goals, challenges and behaviour. The review checklist for businesses came directly from their need to speed up application review.'], figs:[['pf_personas','Business and applicant personas']]},
    {id:'journey', title:'Journey map', body:['A journey map traced the end-to-end application process for both sides and exposed the key touchpoints and pain points.'], figs:[['pf_journey','Customer journey map']]},
    {id:'wireframes', title:'Wireframes', body:['Low to mid-fidelity wireframes were tested with users to validate layout and functionality before development.'], figs:[['pf_wire','Wireframes']]},
    {id:'design', title:'Final design', figs:[['pf_1','Onboarding'],['pf_2','Listings and applications']]}
   ],
   status:'Delivered', findings:[['Businesses needed to review applications faster.', 'A review checklist and quick swipe actions to shortlist or decline applicants.'], ['Job seekers were put off by building a full profile before browsing.', 'Separate onboarding for each side: Apply for jobs you want, and Find the best applicants.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: applying for a job or shortlisting a candidate.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from opening a listing to applying, or to a shortlist.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: mis-swipes and incomplete applications.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: applications sent and businesses posting again.']],
   outcome:'User-tested designs for both sides of hiring. Job seekers browse without paperwork, and businesses get a checklist that speeds up shortlisting.',
   learnings:[['Test and iterate','Early testing led to better, user-validated outcomes.'],['Form meets function','Balancing aesthetics with usability made the experience seamless.'],['Design for growth','Scalable, flexible systems can evolve with the product.']]},

  {slug:'quick-score-pro', title:'Quick Score Pro', who:'Sports clubs', client:'Quick Score Pro', hue:'#1B3A57', cover:'qsp_cover',
   summary:'Digitising club management and match scoring, from bookings and referee assignment to live scores.',
   tags:['Mobile','Operations','UI'], platform:'Mobile',
   problem:'Club owners organised matches, assigned referees and handled registrations and payments by hand. Referees recorded scores on paper that could be lost, damaged or tampered with.',
   approach:'We digitised the whole process, streamlining match bookings and management to cut admin, speed up scheduling and improve the experience for players and organisers.',
   sections:[{id:'design', title:'Final design', figs:[['qsp_1','Club and match management'],['qsp_2','Scoring screens']]}],
   status:'Delivered', findings:[['Scores kept on paper could be lost, damaged or tampered with.', 'Referees capture scores in the app under Assigned matches, while clubs register matches and players find them.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: registering a match and capturing scores.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from booking a match to a published score.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: score corrections after a match.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: clubs and referees using the app each season.']],
   outcome:'Paper score sheets and manual admin replaced by one app for bookings, referee assignment, registrations, payments and live scoring.',
   learnings:[['UX is never really done','There\u2019s always room to refine after launch.'],['Feedback is a gift','Constructive critique improved the product and the collaboration.'],['Design with scalability in mind','Planning for growth helped prevent UX debt.']]},

  {slug:'huawei-tracker', title:'Mine site tracking', who:'Huawei', hue:'#5B3FA6', cover:'hw_cover',
   summary:'Real-time tracking of people and vehicles on mine sites, so managers know where everyone is when it matters.',
   tags:['Dashboards','Safety','Data'], platform:'Web and mobile',
   problem:'Mine site managers couldn\u2019t reliably see where miners were during the day. After a cave-in or vehicle collision, there was often no clear last known location, slowing emergency response and investigations.',
   approach:'I designed a monitoring system for tracking personnel and vehicles in real time, showing last known location, contact history for COVID-19 protocols and time spent in each zone of the mine.',
   sections:[{id:'design', title:'Final design', figs:[['hw_1','Live site map'],['hw_2','Dashboards and reporting']]}],
   status:'Delivered', findings:[['After an incident there was often no clear last known location for miners.', 'A live site map with worker cards, a heat map of activity and worker profiles on mobile.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: finding a person\u2019s last known location.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from an alert to locating the right person.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: wrong zone or person selected.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: managers checking the dashboard every shift.']],
   outcome:'Managers gained real-time visibility of every person and vehicle on site, including last known location, contact history and time in each zone, supporting faster emergency response.',
   learnings:[['Cognitive load is real','Simplifying choices and visuals reduced friction and boosted task completion.'],['Defaults guide behaviour','Smarter defaults helped people complete tasks faster and more accurately.'],['Emotional design matters','Thoughtful copy and transitions made the experience more human.']]},

  {slug:'vikela-portal', title:'Smart safe portal', who:'Vikela Tech', hue:'#3E7B3A', cover:'vk_cover',
   summary:'One portal for businesses to manage smart safes: settings, live activity, devices, receipts and cash counts.',
   tags:['Web app','Dark UI','Accessibility'], platform:'Web and mobile',
   problem:'Businesses needed one place to run their smart safes: customise settings, monitor activity in real time, add or remove devices, print receipts and accurately track deposited bills.',
   approach:'I designed a centralised portal covering each of these tasks, documented with annotated wireframes and specs so design intent carried through to build.',
   sections:[{id:'design', title:'Final design', figs:[['vk_1','Dashboard'],['vk_2','Device and transaction views']]}],
   status:'Delivered', findings:[['Safe operations were spread across separate tasks and tools.', 'One dark-themed portal with devices, transactions and permissions, using high-contrast green for status.']], metrics:[['Task success rate', '', 'Share of people who reach their goal without help. Here: managing a safe and checking its activity.'], ['Time on task', '', 'How long an action takes from start to finish. Shorter usually means a smoother flow. Here: from signing in to finding a transaction.'], ['Error rate', '', 'How often people slip up, such as wrong taps or invalid entries, before they finish. Here: wrong device or permission changes.'], ['Conversion and retention', '', 'How many people complete key actions, like signing up or paying, and how many come back. Here: businesses running their safes through the portal.']],
   outcome:'One accessible portal for every smart safe task, handed over with annotated specs so the build matched the design.',
   learnings:[['Clear documentation','Annotated wireframes and specs carried design intent into implementation.'],['Accessibility helps everyone','Screen reader, contrast and keyboard support improved usability for all users.'],['Colour isn\u2019t enough','Pairing visual indicators with text or patterns made status clearer.']]}
];